Removal of run_cmds and module_utils. Closes #68.
quipucords/rho pull request #119
Opened 2017-07-31 19:46 UTC by chambridge

2017-07-31 21:22 UTC, noahl requested changes
This looks awesome!! I think it will need some very small changes for the JBoss PR, but I'm very excited to get rid of this much code.

2017-07-31 21:22 UTC, noahl commented on library/spit_results.py
> +    class PkgInfo(object):
I think this class is code from a different PR that is in here because we haven't merged the other one yet. Is that right? It still looks good to me.

2017-07-31 21:22 UTC, noahl commented on library/spit_results.py
> +            try:
Not necessary now that the JBoss PR has been merged.

2017-07-31 21:22 UTC, noahl commented on test/test_spit_results.py
> +            "vals": [{'fact1': 'value1',
This will also need minor changes to adapt to the JBoss PR.

2017-08-01 16:45 UTC, chambridge commented on library/spit_results.py
> +    class PkgInfo(object):
yes, this is from the redhat-packages PR.

2017-08-01 16:46 UTC, chambridge commented on library/spit_results.py
> +            try:
I've merged the JBoss code in master into this branch now.

2017-08-01 16:46 UTC, chambridge commented on test/test_spit_results.py
> +            "vals": [{'fact1': 'value1',
Updated for changes to master.

2017-08-01 17:46 UTC, noahl approved these changes

2017-08-01 17:48 UTC, merged